<?php

namespace AppBundle\Repository;

/**
 * lienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lienRepository extends \Doctrine\ORM\EntityRepository
{
}
